project: 
  type: website

website:
  title: "Ash Brandenburg - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: false
  repo-url: https://aboss-us.github.io/aboss-us.github.io-/
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Ash_B 2026©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/ash-brand2025/

  navbar:
    background: primary
    search: false
    right:
      - text: "Home"
        file: index.qmd
      - text: "Resume"
        file: resume.pdf

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

