project: 
  type: website

website:
  title: "Ash Brandenburg - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://aboss-us.github.io/aboss-us.github.io-/
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Ash_B 2026©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/ash-brand2025/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.pdf
      - text: "Data Cleansing"
        file: cleansing.qmd
  
  # learn more about navication here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "Data Cleansing"
      style: "docked"
      background: light
      contents:
        - text: "Data Cleansing"
          file: cleansing.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing_Projects/project2.qmd


    - title: "Data Exploration"
      style: "docked"
      background: light
      contents:
        - text: "Data Exploration"
          file: exploration.qmd
        - text: "---"
        - text: "Project 1"
          file: Exploration_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Exploration_Projects/project2.qmd


format:  
  html:
    theme: cosmo
    css: styles.css
    toc: true



C:\Users\ashle\Documents\GitHub\aboss-us.github.io-